[build]
  publish = "public"
  command = "npm run build"
  
[build.environment]
  NODE_VERSION = "10"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline'; *.google-analytics.com nooby.dev *.cloudfront.net;"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"