backend:
  name: github
  # change repo to your git repository url
  repo: dekiakbar/noobydev

media_folder: static/images/blog
public_folder: /images/blog

collections:
  - name: settings
    label: Settings
    media_folder: static/images/admin
    public_folder: /images/admin
    files:
      - name: config
        label: Config
        file: site-meta-data.json
        fields:
          - widget: string
            name: title
            label: Site Title
            required: true
          - widget: string
            name: language
            label: Site Language
            required: true
          - widget: string
            name: siteUrl
            label: Website URL
            required: true
          - widget: string
            name: keyword
            label: Meta Keyword
            required: true
          - widget: string
            name: twitterUsername
            label: Twitter Username
            required: true
          - widget: image
            name: image
            label: Open Graph Image
            required: false
            media_library:
              config:
                multiple: false
          - widget: text
            name: description
            label: Description
            default: ''
            required: false
          - widget: object
            name: home
            label: Homepage Options
            fields:
              - widget: string
                name: title
                label: Title
                default: ''
                required: false
              - widget: markdown
                name: description
                label: Description
                default: ''
                required: false
  - name: blog
    label: Blog
    folder: _data/blog
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    create: true
    fields:
      - {
          label: Template,
          name: template,
          widget: hidden,
          default: BlogPost,
        }
      - name: path
        label: Path
        widget: string
        pattern: [/blog/]
        hint: "Path must start with /"
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - label: Meta Description
        name: metaDescription
        widget: text
        required: false
      - label: Meta Keyword
        name: metaKeyword
        widget: text
        required: false
      - label: Tags
        name: tags
        widget: text
        required: false
      - label: Featured Image
        name: thumbnail
        widget: image
        hint: "Image size 1280x800 works best :)"
        required: false
        media_library:
          config:
            multiple: false
      - { name: body, label: Body, widget: markdown }
